
-- ===========================================================
-- DROP
-- ===========================================================    
-- alter table if exists person_alias 
--    drop constraint if exists person_alias_person_fk;
-- 
-- drop table if exists person cascade;
-- drop table if exists person_alias cascade;

    
-- ===========================================================
-- CREATE
-- ===========================================================    

create table IF NOT EXISTS person (
   id bigint generated by default as identity,
    birth date,
    name text,
    properties jsonb,
    status varchar(255),
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS person_name_idx
    ON conciliator.person(name);

create table  IF NOT EXISTS person_alias (
   id bigint generated by default as identity,
    alias text,
    type varchar(255),
    person_id bigint,
    CONSTRAINT person_alias_pkey PRIMARY KEY (id),
    CONSTRAINT person_alias_unq_idx UNIQUE (alias, type, id),
    CONSTRAINT person_alias_person_fk FOREIGN KEY (person_id)
        REFERENCES conciliator.person (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE    
);

   

