
-- ===========================================================
-- DROP
-- ===========================================================    
alter table if exists person_alias 
   drop constraint if exists person_alias_person_fk;

drop table if exists person cascade;
drop table if exists person_alias cascade;

    
-- ===========================================================
-- CREATE
-- ===========================================================    

create table person (
   id bigint generated by default as identity,
    birth date,
    name text,
    properties jsonb,
    status varchar(255),
    primary key (id)
);


create table person_alias (
   id bigint generated by default as identity,
    alias text,
    type varchar(255),
    person_id bigint,
    primary key (id)
);

create index person_name_idx on person(name);
 
    
alter table if exists person_alias 
   add constraint person_alias_unq_idx unique (alias, type, id);
   
   
alter table if exists person_alias 
   add constraint person_alias_person_fk 
   foreign key (person_id) 
   references person
   ON DELETE CASCADE
   ON UPDATE CASCADE;
   
   